version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for nuget
  - package-ecosystem: "nuget"
    directory: "src/megaphone.resources/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "src/megaphone.resources.tests/"
    schedule:
      interval: "daily"