apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: feed-requests
spec:
  type: bindings.redis
  metadata:
  - name: redisHost
    value: dapr_redis:6379
  - name: redisPassword
    value: ""