apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: crawl-requests
  namespace: default
spec:
  type: bindings.rabbitmq
  metadata:
  - name: queueName
    value: "crawl-requests"
  - name: host
    value: "amqp://guest:guest@rabbitmq:5672"
  - name: durable
    value: "true"
  - name: deletedWhenUnused
    value: "true"
  - name: ttlInSeconds
    value: 600