apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: feed-state
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: dapr_redis_dapr-dev-container:6379
  - name: redisPassword
    value: ""